#!/bin/bash

# ---- OpenFOAM + Spack -------------------------------------------------------
source /opt/spack/share/spack/setup-env.sh          # enable Spack
eval "$(spack load --sh openfoam@2312)"             # inject FOAM env vars
export PATH=$WM_PROJECT_DIR/wmake:$PATH
#   –OR, if you prefer–
# source "$(spack location -i openfoam@2312)/etc/bashrc"

# ---- run the tutorial -------------------------------------------------------

cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

canCompile || exit 0    # Dynamic code

restore0Dir

runApplication blockMesh

runApplication $(getApplication) -withFunctionObjects -writePhi -writephi -writep

runApplication postProcess -func "(streamFunction writeCellCentres)"

runApplication foamToVTK -time 0

#------------------------------------------------------------------------------
